dojo:
    resource: "@dojoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }
