app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


user_register:
    path:    /user/register
    defaults: { _controller: AppBundle:Registration:register }


messagerie:
    path:    /messagerie
    defaults: { _controller: AppBundle:Default:messagerie }

messagerie_new:
    path:    /messagerie/new
    defaults: { _controller: AppBundle:Default:messagerieNew }